version: '3.7'
volumes:
  mariadb-volume:
  www-volume:
services:
  php-apache2: 
    build:
      context: ./
      dockerfile: devbox.dockerfile
    ports: 
      - 80:80
    volumes:
      - www-volume:/var/www/html
  
  mariadb:
    image: mariadb:10.5.2
    volumes: 
      - mariadb-volume:/var/lib/mysql
    environment:
      TZ: "America/New_York"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'testpassword'
      MYSQL_DATABASE: 'wordpress'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - 'mariadb:db'
    ports:
      - 8081:80
